name = "Additive"
author = "SkywardMC"
version = "1.35.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49f6109c5cb3a261b8f77a0444134b6fedaa2a7de3e444bb518ade5d91349ae5"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
