name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "738066cbe3ea36685168f8b4446e645286d6df3fa7a6395bfc0c56047440c588"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
