name = "Additive"
author = "SkywardMC"
version = "1.35.1+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb9913d299c9a9327607b5f0402e5d9b43aa35523a90077fce025961a5880fc4"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
