name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29c3bb6f36e05a3d538bd7175b7f6705c19b06f44031d47521bf6b1f8761f01e"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
