name = "Additive"
author = "SkywardMC"
version = "1.35.1+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7fcc01f05ceb14920ca885ea94b77abb958fbdf2d0e928473d58e2ea54812ef"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
