name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.5.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b5a49d9662f5dc122bb2eb3b917802c635f3d3463623ccb65b5b52c5b2e462d"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
