name = "Additive"
author = "SkywardMC"
version = "1.35.1+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8827f5d82aa1b4edc25e53b2d178a687af189916f1903584ce885f5293097274"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
