name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b15277a906dd041b16d3f29aa74bd590f82f7934de4483a77de368b7bcf73e30"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
