name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f11806f4faa11095a6091ce94eb3204f8bb37799ba82ea911b89d81774f7854"

[versions]
fabric = "0.16.14"
minecraft = "1.21.4"
