name = "Additive"
author = "SkywardMC"
version = "1.35.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14649f4ef4ccb9e147dfde6bc8b647cc42a1557f213a0783f017ba22d567e0a2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
