name = "Additive"
author = "SkywardMC"
version = "1.35.1+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad2d8bd4f796340e5f4911da3c3c1f7ae0c4ff47d6128026b3e2355b83dbe8f2"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
