name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8479ebd458aa5eedf55a850623a2b7be45fcf1fe3f5718d5ddb17e55bb176fc"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
