name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6225b74f9cbf28613a1a4016d3bc435c683d5f9152e59a7acd45218b0e884e7b"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
