name = "Additive"
author = "SkywardMC"
version = "1.36.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8778b9b0d0a8b368fa5f473dd0fad0db60df30d97cfd7d9bb84134e6583fc551"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
